In [6]:
import numpy as np

def bag_of_words(sentences):
    tokenized_sentences = [sentence.lower().split() for sentence in sentences]
    flat_words = [word for sublist in tokenized_sentences for word in sublist]

    vocabulary = sorted(set(flat_words))
    word_to_index = {word: i for i, word in enumerate(vocabulary)}

    bow_matrix = np.zeros((len(sentences), len(vocabulary)), dtype=int)

    for i, sentence in enumerate(tokenized_sentences):
        for word in sentence:
            if word in word_to_index:
                bow_matrix[i, word_to_index[word]] += 1

    return vocabulary, bow_matrix


In [7]:
corpus = ["This movie is awesome awesome",
          "I do not say is good but neither awesome", 
          "Awesome? Only a fool can say that"]

vocabulary, bow_matrix = bag_of_words(corpus)

print("Vocabulary : ", vocabulary)
print("bow matrix :\n", bow_matrix)

Vocabulary :  ['a', 'awesome', 'awesome?', 'but', 'can', 'do', 'fool', 'good', 'i', 'is', 'movie', 'neither', 'not', 'only', 'say', 'that', 'this']
bow matrix :
 [[0 2 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1]
 [0 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 0]
 [1 0 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0]]
