In [4]:
import numpy as np 

def one_hot_encoding(sentence):

    words = sentence.lower().split()
    vocabulary = sorted(set(words))

    words_to_index = {word:i for i,word in enumerate(vocabulary)}
    one_hot_matrix = np.zeros((len(words), len(vocabulary)), dtype=int)

    for i, word in enumerate(words):
        one_hot_matrix[i, words_to_index[word]] = 1

    return one_hot_matrix, vocabulary




In [5]:
sentence = "Should we go to a pizzeria or do you prefer a restaurant?"
one_hot_matrix, vocabulary = one_hot_encoding(sentence)

print("Vocabulary: ", vocabulary)
print("One hot encoding matrix :\n", one_hot_matrix)

Vocabulary:  ['a', 'do', 'go', 'or', 'pizzeria', 'prefer', 'restaurant?', 'should', 'to', 'we', 'you']
One hot encoding matrix :
 [[0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]]


In [6]:
one_hot_matrix[0, 7]

np.int64(1)